import plistlib
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
import heartbeat  # noqa: E402
import schedules  # noqa: E402
import sync_schedules  # noqa: E402

HEADER = (
    "| Label | Routine | Command | Kind | Timing | Enabled | Log | Env | Options |\n"
    "|---|---|---|---|---|---|---|---|---|\n"
)

FIXED_ROW = (
    "| com.test.dashboard | Dashboard | `/usr/bin/python3 /tmp/dash.py --brain /tmp/brain` "
    "| fixed-interval | 06:05 | yes | ~/Library/Logs/dash.log ; ~/Library/Logs/dash-error.log "
    "| PATH=/usr/bin; HOME=~ | run-at-load=true |\n"
)

POLL_ROW = (
    "| com.test.sweep | Capture sweep | `/usr/bin/python3 /tmp/sweep.py` | poll | 15m | yes "
    "| /tmp/sweep.log | PATH=/usr/bin | — |\n"
)

UNMANAGED_PLIST = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
    '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    '<plist version="1.0">\n<dict>\n'
    "\t<key>Label</key>\n\t<string>com.thirdparty.thing</string>\n"
    "\t<key>ProgramArguments</key>\n\t<array>\n\t\t<string>/bin/true</string>\n\t</array>\n"
    "\t<key>StartInterval</key>\n\t<integer>60</integer>\n"
    "</dict>\n</plist>\n"
)


def table(*rows):
    return HEADER + "".join(rows)


class ScheduleFixture(unittest.TestCase):
    """Every test gets its own tmp Brain and its own tmp LaunchAgents dir.

    The real ~/Library/LaunchAgents is never a target: `agents_dir` is
    injected everywhere, and `sync_schedules.DEFAULT_LAUNCH_AGENTS` is only
    ever read by `main()`.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        root = Path(self._tmp.name)
        self.brain = root / "brain"
        (self.brain / "config").mkdir(parents=True)
        self.agents_dir = root / "LaunchAgents"
        self.agents_dir.mkdir()

    def tearDown(self):
        self._tmp.cleanup()

    def write_table(self, text):
        (self.brain / "config" / "schedules.md").write_text(text)

    def sync(self, **kwargs):
        kwargs.setdefault("load", False)
        kwargs.setdefault("show_diff", False)
        return sync_schedules.sync(self.brain, self.agents_dir, **kwargs)

    def plist(self, label):
        with open(self.agents_dir / f"{label}.plist", "rb") as fh:
            return plistlib.load(fh)


class TestRowRoundTrip(ScheduleFixture):
    def test_row_round_trips_to_a_valid_managed_plist(self):
        self.write_table(table(FIXED_ROW))
        self.sync()

        path = self.agents_dir / "com.test.dashboard.plist"
        self.assertTrue(path.exists())
        self.assertTrue(sync_schedules.is_managed(path))

        data = self.plist("com.test.dashboard")
        self.assertIs(data[sync_schedules.MARKER_KEY], True)
        self.assertEqual(data["Label"], "com.test.dashboard")
        self.assertEqual(
            data["ProgramArguments"],
            ["/usr/bin/python3", "/tmp/dash.py", "--brain", "/tmp/brain"],
        )
        self.assertEqual(data["StandardOutPath"], str(Path.home() / "Library/Logs/dash.log"))
        self.assertEqual(data["StandardErrorPath"], str(Path.home() / "Library/Logs/dash-error.log"))
        self.assertEqual(data["EnvironmentVariables"], {"PATH": "/usr/bin", "HOME": str(Path.home())})
        self.assertIs(data["RunAtLoad"], True)

        text = path.read_text()
        self.assertIn("Generated by goals-os-engine scripts/sync_schedules.py", text)
        self.assertIn("config/schedules.md", text)

    def test_resync_is_idempotent_and_rewrites_nothing(self):
        self.write_table(table(FIXED_ROW))
        self.sync()
        path = self.agents_dir / "com.test.dashboard.plist"
        before = path.read_text()
        mtime = path.stat().st_mtime_ns

        plan = self.sync()
        self.assertEqual([i["label"] for i in plan["unchanged"]], ["com.test.dashboard"])
        self.assertEqual(plan["create"], [])
        self.assertEqual(plan["update"], [])
        self.assertEqual(path.read_text(), before)
        self.assertEqual(path.stat().st_mtime_ns, mtime)

    def test_changed_timing_updates_the_plist(self):
        self.write_table(table(FIXED_ROW))
        self.sync()
        self.write_table(table(FIXED_ROW.replace("| 06:05 |", "| 07:30 |")))
        plan = self.sync()
        self.assertEqual([i["label"] for i in plan["update"]], ["com.test.dashboard"])
        self.assertEqual(self.plist("com.test.dashboard")["StartCalendarInterval"],
                         {"Hour": 7, "Minute": 30})


class TestFixedIntervalRendering(ScheduleFixture):
    def test_clock_time_renders_a_single_start_calendar_interval_dict(self):
        self.write_table(table(FIXED_ROW))
        self.sync()
        data = self.plist("com.test.dashboard")
        self.assertEqual(data["StartCalendarInterval"], {"Hour": 6, "Minute": 5})
        self.assertNotIn("StartInterval", data)

    def test_weekday_range_renders_one_entry_per_day(self):
        row = ("| com.test.sonia | — | `/bin/echo hi` | fixed-interval | Mon-Fri 14:00 | yes "
               "| /tmp/s.log | — | cwd=/tmp |\n")
        self.write_table(table(row))
        self.sync()
        data = self.plist("com.test.sonia")
        self.assertEqual(
            data["StartCalendarInterval"],
            [{"Weekday": d, "Hour": 14, "Minute": 0} for d in (1, 2, 3, 4, 5)],
        )
        self.assertEqual(data["WorkingDirectory"], "/tmp")

    def test_single_named_weekday_renders_a_dict_with_weekday_zero_for_sunday(self):
        row = ("| com.test.dream | — | `/bin/echo hi` | fixed-interval | Sun 20:07 | yes "
               "| /tmp/d.log | — | — |\n")
        self.write_table(table(row))
        self.sync()
        self.assertEqual(self.plist("com.test.dream")["StartCalendarInterval"],
                         {"Weekday": 0, "Hour": 20, "Minute": 7})

    def test_cadence_word_row_renders_no_job(self):
        row = "| planning | Planning session | — | fixed-interval | weekly | yes | — | — | — |\n"
        self.write_table(table(row))
        plan = self.sync()
        self.assertEqual(plan["create"], [])
        self.assertEqual(list(self.agents_dir.iterdir()), [])


class TestPollRendering(ScheduleFixture):
    def test_poll_row_renders_start_interval_in_seconds(self):
        self.write_table(table(POLL_ROW))
        self.sync()
        data = self.plist("com.test.sweep")
        self.assertEqual(data["StartInterval"], 900)
        self.assertNotIn("StartCalendarInterval", data)
        self.assertIs(data[sync_schedules.MARKER_KEY], True)

    def test_poll_row_is_not_heartbeat_checkable(self):
        self.write_table(table(POLL_ROW))
        scheds = schedules.parse_schedules(schedules.schedules_path(self.brain))
        self.assertEqual(
            schedules.cadence_by_routine(scheds),
            {"Capture sweep": {"cadence_days": None, "checkable": False}},
        )


class TestRemovedRow(ScheduleFixture):
    def test_removed_row_disables_only_its_managed_job(self):
        self.write_table(table(FIXED_ROW, POLL_ROW))
        self.sync()
        (self.agents_dir / "com.thirdparty.thing.plist").write_text(UNMANAGED_PLIST)

        self.write_table(table(FIXED_ROW))
        plan = self.sync()

        self.assertEqual([i["label"] for i in plan["remove"]], ["com.test.sweep"])
        self.assertFalse((self.agents_dir / "com.test.sweep.plist").exists())
        self.assertTrue((self.agents_dir / "com.test.dashboard.plist").exists())
        self.assertTrue((self.agents_dir / "com.thirdparty.thing.plist").exists())

    def test_disabled_row_is_removed_too(self):
        self.write_table(table(FIXED_ROW))
        self.sync()
        self.write_table(table(FIXED_ROW.replace("| yes |", "| no |")))
        plan = self.sync()
        self.assertEqual([i["label"] for i in plan["remove"]], ["com.test.dashboard"])
        self.assertFalse((self.agents_dir / "com.test.dashboard.plist").exists())


class TestUnmanagedIsUntouchable(ScheduleFixture):
    def test_unmanaged_plist_is_left_byte_identical(self):
        path = self.agents_dir / "com.thirdparty.thing.plist"
        path.write_text(UNMANAGED_PLIST)
        before = path.read_bytes()

        self.write_table(table(FIXED_ROW))
        self.sync()

        self.assertEqual(path.read_bytes(), before)

    def test_label_collision_with_an_unmanaged_plist_is_refused_before_any_write(self):
        collide = self.agents_dir / "com.test.dashboard.plist"
        collide.write_text(UNMANAGED_PLIST)
        before = collide.read_bytes()

        self.write_table(table(FIXED_ROW, POLL_ROW))
        with self.assertRaises(sync_schedules.RefusedError) as ctx:
            self.sync()

        self.assertIn("NOT Managed", str(ctx.exception))
        self.assertEqual(collide.read_bytes(), before)
        # The other, perfectly good row was not written either.
        self.assertFalse((self.agents_dir / "com.test.sweep.plist").exists())

    def test_is_managed_is_false_for_unparseable_and_unmarked_files(self):
        junk = self.agents_dir / "junk.plist"
        junk.write_text("not a plist at all")
        self.assertFalse(sync_schedules.is_managed(junk))

        unmarked = self.agents_dir / "com.thirdparty.thing.plist"
        unmarked.write_text(UNMANAGED_PLIST)
        self.assertFalse(sync_schedules.is_managed(unmarked))


class TestMalformedRows(ScheduleFixture):
    def _assert_rejected(self, row, fragment):
        self.write_table(table(FIXED_ROW, row))
        with self.assertRaises(schedules.ScheduleError) as ctx:
            self.sync()
        self.assertIn(fragment, str(ctx.exception))
        # Nothing partially written — not even the valid row above it.
        self.assertEqual(list(self.agents_dir.iterdir()), [])

    def test_unknown_kind(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | whenever | 06:00 | yes | /tmp/x.log | — | — |\n",
            "Kind must be one of",
        )

    def test_unparseable_clock_time(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | fixed-interval | half past six | yes | /tmp/x.log | — | — |\n",
            "Timing must be",
        )

    def test_poll_row_without_an_interval(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | poll | 06:00 | yes | /tmp/x.log | — | — |\n",
            "poll Timing must be an interval",
        )

    def test_out_of_range_clock_time(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | fixed-interval | 25:00 | yes | /tmp/x.log | — | — |\n",
            "not a valid 24h clock time",
        )

    def test_bad_enabled_value(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | fixed-interval | 06:00 | maybe | /tmp/x.log | — | — |\n",
            "Enabled must be yes or no",
        )

    def test_unknown_option_key(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | fixed-interval | 06:00 | yes | /tmp/x.log | — | nice=5 |\n",
            "unknown Options key",
        )

    def test_wrong_cell_count(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | fixed-interval | 06:00 | yes |\n",
            "expected 9",
        )

    def test_duplicate_label(self):
        self.write_table(table(FIXED_ROW, FIXED_ROW))
        with self.assertRaises(schedules.ScheduleError) as ctx:
            self.sync()
        self.assertIn("duplicate Label", str(ctx.exception))
        self.assertEqual(list(self.agents_dir.iterdir()), [])

    def test_enabled_fixed_interval_job_needs_a_clock_not_a_cadence_word(self):
        self._assert_rejected(
            "| com.test.x | — | `/bin/echo hi` | fixed-interval | weekly | yes | /tmp/x.log | — | — |\n",
            "needs a clock time in Timing",
        )

    def test_every_problem_is_reported_not_just_the_first(self):
        self.write_table(table(
            "| com.test.a | — | `/bin/echo hi` | whenever | 06:00 | yes | /tmp/a.log | — | — |\n",
            "| com.test.b | — | `/bin/echo hi` | fixed-interval | nonsense | yes | /tmp/b.log | — | — |\n",
        ))
        with self.assertRaises(schedules.ScheduleError) as ctx:
            self.sync()
        problems = "\n".join(ctx.exception.problems)
        self.assertIn("line 3", problems)  # both bad rows are named, not just the first
        self.assertIn("line 4", problems)
        self.assertIn("Kind must be one of", problems)
        self.assertIn("Timing must be", problems)

    def test_missing_schedules_file_fails_loudly(self):
        with self.assertRaises(schedules.ScheduleError) as ctx:
            self.sync()
        self.assertIn("does not exist", str(ctx.exception))


class TestDryRun(ScheduleFixture):
    def test_dry_run_writes_nothing(self):
        self.write_table(table(FIXED_ROW, POLL_ROW))
        plan = self.sync(dry_run=True)
        self.assertEqual(len(plan["create"]), 2)
        self.assertEqual(list(self.agents_dir.iterdir()), [])

    def test_dry_run_diffs_a_changed_job(self):
        self.write_table(table(FIXED_ROW))
        self.sync()
        self.write_table(table(FIXED_ROW.replace("| 06:05 |", "| 07:30 |")))
        plan = self.sync(dry_run=True)
        text = sync_schedules.format_plan(plan, show_diff=True)
        self.assertIn("update    com.test.dashboard", text)
        self.assertIn("-\t\t<integer>6</integer>", text)
        self.assertIn("+\t\t<integer>7</integer>", text)


class TestHeartbeatReadsCadenceFromSchedules(ScheduleFixture):
    """ADR-0030: cadence left the Engine; heartbeat.py reads it from the Brain."""

    def _routine_state(self, **rows):
        lines = ["| Routine | Last run |", "|---|---|"]
        lines += [f"| {k} | {v} |" for k, v in rows.items()]
        (self.brain / "config" / "routine-state.md").write_text("\n".join(lines) + "\n")

    def test_cadence_comes_from_schedules_md_not_the_manifest(self):
        self.write_table(table(
            "| dashboard | Dashboard | — | fixed-interval | daily | yes | — | — | — |\n"
        ))
        self._routine_state(Dashboard="never")
        overdue = heartbeat.overdue_for_brain(self.brain)
        self.assertEqual([o["routine"] for o in overdue], ["Dashboard"])
        self.assertEqual(overdue[0]["cadence_days"], 1)

    def test_manifest_no_longer_carries_a_cadence_column(self):
        manifest = heartbeat.parse_manifest()
        self.assertTrue(manifest)
        self.assertNotIn("Cadence", manifest[0])

    def test_routine_with_no_schedule_is_never_flagged(self):
        self.write_table(HEADER)
        self._routine_state(Dashboard="never", Triage="never")
        self.assertEqual(heartbeat.overdue_for_brain(self.brain), [])

    def test_poll_scheduled_routine_is_never_flagged(self):
        self.write_table(table(
            "| triage | Triage | — | poll | 15m | yes | — | — | — |\n"
        ))
        self._routine_state(Triage="never")
        self.assertEqual(heartbeat.overdue_for_brain(self.brain), [])

    def test_disabled_schedule_is_never_flagged(self):
        self.write_table(table(
            "| dashboard | Dashboard | — | fixed-interval | daily | no | — | — | — |\n"
        ))
        self._routine_state(Dashboard="never")
        self.assertEqual(heartbeat.overdue_for_brain(self.brain), [])

    def test_clock_timing_implies_a_daily_cadence(self):
        self.write_table(table(FIXED_ROW))
        self._routine_state(Dashboard="never")
        overdue = heartbeat.overdue_for_brain(self.brain)
        self.assertEqual(overdue[0]["cadence_days"], 1)

    def test_missing_schedules_file_is_reported_not_fatal_for_dashboard(self):
        self._routine_state(Dashboard="never")
        self.assertEqual(heartbeat.overdue_for_brain(self.brain), [])


class TestStarterScheduleExample(unittest.TestCase):
    """The shipped starter table must reproduce the manifest's due-check set.

    `protocols/examples/schedules.md` is what the Brain Template ships as a
    fresh Brain's `config/schedules.md` (ADR-0030's required bootstrap), so it
    has to keep Heartbeat working out of the box.
    """

    EXAMPLE = Path(__file__).parent.parent / "protocols" / "examples" / "schedules.md"

    def test_example_parses(self):
        scheds = schedules.parse_schedules(self.EXAMPLE)
        self.assertEqual(len(scheds), 18)

    def test_example_declares_no_jobs(self):
        scheds = schedules.parse_schedules(self.EXAMPLE)
        self.assertEqual([s.label for s in scheds if s.renders_job], [])

    def test_every_manifest_routine_has_a_schedule(self):
        scheds = schedules.parse_schedules(self.EXAMPLE)
        scheduled = {s.routine for s in scheds}
        manifest_routines = {row["Routine"] for row in heartbeat.parse_manifest()}
        self.assertEqual(manifest_routines - scheduled, set())

    def test_flags_only_implemented_heartbeat_checkable_routines(self):
        manifest = heartbeat.parse_manifest()
        scheds = schedules.parse_schedules(self.EXAMPLE)
        routine_state = {row["Routine"]: "never" for row in manifest}
        overdue = heartbeat.compute_overdue(manifest, routine_state, scheds)
        self.assertEqual(
            {item["routine"] for item in overdue},
            {"Triage", "Dashboard", "Version control", "Planning session", "Daily note",
             "Close daily note", "Compile", "Graduation check", "Rule learning",
             "Ticket normalization"},
        )


if __name__ == "__main__":
    unittest.main()
