#!/usr/bin/env python3
"""Scheduler Adapter — reconcile ~/Library/LaunchAgents/ to a Brain's config/schedules.md.

ADR-0007 layer 2. Parses the Brain's `config/schedules.md` (see
`scripts/schedules.py` and `protocols/schedules.md`), renders one **Managed**
`.plist` per enabled row that names a Command, writes it into the LaunchAgents
directory, and `launchctl bootstrap`s it. Idempotent: re-running converges the
directory to the table, and Managed jobs no longer in the table are booted out
and deleted.

Safety, in order of importance:

1. **An Unmanaged plist is never touched.** Managed means the file carries the
   `GoalsOSManaged` marker key, so Managed-vs-Unmanaged is decidable from the
   file alone. A table row whose Label collides with a hand-written plist is a
   hard refusal — nothing is written, nothing is loaded.
2. **Whole-table validation before any filesystem write.** A malformed row
   aborts the whole run; the directory is left exactly as it was.
3. **A removal-only plan is refused.** A plan that removes jobs and creates
   none can only ever destroy live state — the shape a truncated, stubbed or
   mis-titled table produces. Deleting a row on purpose is still possible,
   with `--allow-removals`.
4. **`--dry-run`** prints the plan (and a unified diff per changed file) and
   writes nothing.

Out of scope, by ticket: what any job *does*, and firing an unattended Claude
session. This adapter schedules a trigger — it is not a session runner. A
consumer needing an unattended agent session must still supply the runner
(e.g. `claude -p <command>`) as the row's Command.

Pure Python, zero LLM calls.
"""

import argparse
import datetime as dt
import difflib
import os
import plistlib
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import schedules as schedules_mod  # noqa: E402

MARKER_KEY = "GoalsOSManaged"
GENERATED_BY = "goals-os-engine scripts/sync_schedules.py"
DEFAULT_LAUNCH_AGENTS = Path.home() / "Library" / "LaunchAgents"

# Semantic keys compared when deciding whether a plist changed, and when
# diffing a generated plist against a hand-written original during migration.
SEMANTIC_KEYS = (
    "Label", "ProgramArguments", "WorkingDirectory", "StartCalendarInterval",
    "StartInterval", "RunAtLoad", "StandardOutPath", "StandardErrorPath",
    "EnvironmentVariables",
)


class RefusedError(Exception):
    """A guard tripped. Nothing has been written."""


def build_plist_dict(sched) -> dict:
    """The plist body for one Schedule, marker included."""
    body = {"Label": sched.label, "ProgramArguments": list(sched.command)}
    if sched.working_dir:
        body["WorkingDirectory"] = sched.working_dir
    if sched.kind == schedules_mod.KIND_POLL:
        body["StartInterval"] = sched.interval_seconds
    else:
        body["StartCalendarInterval"] = (
            sched.calendar[0] if len(sched.calendar) == 1 else list(sched.calendar)
        )
    if sched.run_at_load is not None:
        body["RunAtLoad"] = sched.run_at_load
    if sched.stdout:
        body["StandardOutPath"] = sched.stdout
    if sched.stderr:
        body["StandardErrorPath"] = sched.stderr
    if sched.env:
        body["EnvironmentVariables"] = dict(sched.env)
    body[MARKER_KEY] = True
    return body


def render_plist(sched, brain_path=None, now=None) -> str:
    """Render the full plist file text: generated-by header comment + body."""
    now = now or dt.datetime.now()
    source = f"{brain_path}/config/schedules.md" if brain_path else "config/schedules.md"
    xml = plistlib.dumps(build_plist_dict(sched)).decode()
    header = (
        f"<!-- Generated by {GENERATED_BY} from {source}\n"
        f"     at {now.strftime('%Y-%m-%d %H:%M')} — do not hand-edit; edit the table and re-sync.\n"
        f"     {MARKER_KEY} marks this file as adapter-owned. -->\n"
    )
    lines = xml.splitlines(keepends=True)
    # Insert the comment after the <?xml?> and <!DOCTYPE> declarations.
    insert_at = 0
    for i, line in enumerate(lines):
        if line.lstrip().startswith("<plist"):
            insert_at = i
            break
    return "".join(lines[:insert_at]) + header + "".join(lines[insert_at:])


def read_plist(path: Path):
    try:
        with open(path, "rb") as fh:
            return plistlib.load(fh)
    except Exception:
        return None


def is_managed(path: Path) -> bool:
    """Managed iff the plist parses and carries the marker key set true."""
    data = read_plist(path)
    return bool(data) and data.get(MARKER_KEY) is True


def semantic(data: dict) -> dict:
    return {k: data[k] for k in SEMANTIC_KEYS if k in (data or {})}


def plist_path(agents_dir: Path, label: str) -> Path:
    return Path(agents_dir) / f"{label}.plist"


def build_plan(scheds, agents_dir: Path, brain_path=None, now=None) -> dict:
    """Decide what to create/update/remove. Pure — touches nothing.

    Raises RefusedError if a desired Label collides with an Unmanaged plist,
    so the caller aborts before its first write.
    """
    agents_dir = Path(agents_dir)
    desired = {s.label: s for s in scheds if s.renders_job}

    refusals = []
    for label in desired:
        path = plist_path(agents_dir, label)
        if path.exists() and not is_managed(path):
            refusals.append(
                f"{path.name} exists and is NOT Managed (no {MARKER_KEY} marker). "
                f"Refusing to overwrite a hand-written plist."
            )
    if refusals:
        raise RefusedError(
            "Refusing to write — hand-written plists in the way:\n"
            + "\n".join(f"  - {r}" for r in refusals)
            + "\nRemove or rename them by hand first, or drop the row."
        )

    managed_on_disk = {}
    if agents_dir.is_dir():
        for path in sorted(agents_dir.glob("*.plist")):
            if is_managed(path):
                managed_on_disk[path.stem] = path

    create, update, unchanged = [], [], []
    for label, sched in desired.items():
        path = plist_path(agents_dir, label)
        text = render_plist(sched, brain_path=brain_path, now=now)
        if not path.exists():
            create.append({"label": label, "path": path, "text": text, "old": None})
            continue
        current = read_plist(path)
        if semantic(current) == semantic(build_plist_dict(sched)):
            unchanged.append({"label": label, "path": path})
        else:
            update.append({"label": label, "path": path, "text": text,
                           "old": path.read_text()})

    remove = [{"label": label, "path": path}
              for label, path in sorted(managed_on_disk.items())
              if label not in desired]

    return {"create": create, "update": update, "unchanged": unchanged, "remove": remove}


def check_removal_only(plan: dict, allow_removals: bool = False):
    """Refuse a plan that removes Jobs and creates none.

    That plan shape has exactly one meaning — live state goes away and nothing
    replaces it — and it is what a table that lost its rows produces. A
    deliberate deletion says so explicitly with `--allow-removals`.
    """
    if allow_removals or not plan["remove"] or plan["create"]:
        return
    labels = ", ".join(item["label"] for item in plan["remove"])
    raise RefusedError(
        f"Refusing to apply a removal-only plan: it would boot out and delete "
        f"{len(plan['remove'])} Managed job(s) ({labels}) and create none.\n"
        f"That is what a truncated, stubbed or mis-titled config/schedules.md looks like. "
        f"Check the table still holds the rows you expect.\n"
        f"If the deletion is deliberate, re-run with --allow-removals."
    )


def _launchctl(args, verbose=True):
    cmd = ["launchctl"] + args
    result = subprocess.run(cmd, capture_output=True, text=True)
    if verbose and result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        print(f"  launchctl {' '.join(args)} -> {result.returncode} {detail}", file=sys.stderr)
    return result


def bootout(label: str, path: Path, domain: str):
    """Unload a job. bootout first (modern), then legacy unload as a fallback."""
    result = _launchctl(["bootout", f"{domain}/{label}"], verbose=False)
    if result.returncode != 0:
        _launchctl(["unload", str(path)], verbose=False)


def bootstrap(label: str, path: Path, domain: str):
    """Load a job, replacing any already-loaded instance of the same Label."""
    bootout(label, path, domain)
    result = _launchctl(["bootstrap", domain, str(path)])
    if result.returncode != 0:
        _launchctl(["load", str(path)])


def apply_plan(plan: dict, agents_dir: Path, domain: str = None, load: bool = True) -> list:
    """Execute a plan. Every write happens here and nowhere else."""
    agents_dir = Path(agents_dir)
    agents_dir.mkdir(parents=True, exist_ok=True)
    domain = domain or f"gui/{os.getuid()}"
    actions = []

    for item in plan["remove"]:
        if load:
            bootout(item["label"], item["path"], domain)
        item["path"].unlink()
        actions.append(f"removed {item['label']}")

    for item in plan["create"] + plan["update"]:
        item["path"].write_text(item["text"])
        if load:
            bootstrap(item["label"], item["path"], domain)
        actions.append(f"{'created' if item['old'] is None else 'updated'} {item['label']}")

    return actions


def format_plan(plan: dict, show_diff: bool = False) -> str:
    lines = []
    for kind in ("create", "update", "remove"):
        for item in plan[kind]:
            lines.append(f"  {kind:<9} {item['label']}")
    for item in plan["unchanged"]:
        lines.append(f"  unchanged {item['label']}")
    if not lines:
        lines.append("  (nothing to do)")

    if show_diff:
        for item in plan["update"]:
            diff = difflib.unified_diff(
                item["old"].splitlines(keepends=True),
                item["text"].splitlines(keepends=True),
                fromfile=f"a/{item['path'].name}", tofile=f"b/{item['path'].name}",
            )
            lines.append("")
            lines.extend(line.rstrip("\n") for line in diff)
    return "\n".join(lines)


def sync(brain_path: Path, agents_dir: Path, dry_run: bool = False,
         load: bool = True, now: dt.datetime = None, show_diff: bool = True,
         allow_removals: bool = False) -> dict:
    scheds = schedules_mod.parse_schedules(schedules_mod.schedules_path(brain_path))
    plan = build_plan(scheds, agents_dir, brain_path=brain_path, now=now)
    print(f"Schedules: {len(scheds)} row(s), {sum(1 for s in scheds if s.renders_job)} job(s)")
    print(format_plan(plan, show_diff=show_diff))
    # After printing, so the refusal always shows the plan it refused.
    check_removal_only(plan, allow_removals=allow_removals)
    if dry_run:
        print("--dry-run: nothing written.")
        return plan
    actions = apply_plan(plan, agents_dir, load=load)
    if actions:
        print("Applied: " + ", ".join(actions))
    return plan


def parse_args(argv):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--brain", required=True, help="Path to the Brain (contains config/schedules.md)")
    p.add_argument("--launch-agents-dir", default=None,
                   help=f"Target directory for Managed plists (default: {DEFAULT_LAUNCH_AGENTS})")
    p.add_argument("--dry-run", action="store_true", help="Print the plan and diffs; write nothing")
    p.add_argument("--no-load", action="store_true", help="Write plists but do not call launchctl")
    p.add_argument("--allow-removals", action="store_true",
                   help="Permit a plan that removes Managed jobs and creates none "
                        "(refused by default — that is what a gutted table looks like)")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    brain_path = Path(args.brain).expanduser().resolve()
    if not brain_path.is_dir():
        sys.exit(f"Brain path does not exist: {brain_path}")
    agents_dir = Path(args.launch_agents_dir).expanduser() if args.launch_agents_dir else DEFAULT_LAUNCH_AGENTS

    try:
        sync(brain_path, agents_dir, dry_run=args.dry_run, load=not args.no_load,
             allow_removals=args.allow_removals)
    except (schedules_mod.ScheduleError, RefusedError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
